### ISSUE TITLE
Autodecrypt passwords specified in own / user specific properties file

### ISSUE THREAD

**Issue by mierzwid** [neva-dev/gradle-fork-plugin#27]
Make Fork decrypt password, so other plugins like GAP don't have to use forkProps extension to pass properties. 

When fork generates properties file with password encrypted it adds `fp:` prefix to them:
```
fileTransfer.sftp.user=username
fileTransfer.sftp.password={fp:nWVIC40MKSf2ZasfflkOXA==}
```

knowing the peb template it can decode values on the fly, so build script author don't have to pass through in the build file:

```
aem {
    fileTransfer {
        sftp {
            user = forkProps["fileTransfer.sftp.user"]
            password = forkProps["fileTransfer.sftp.password"]
        }
    }
}
```

**Comment by pun-ky** [comment]
I need to think about it 😉 interesting idea

**Comment by mierzwid** [comment]
Make sure Two-Way sync when forking (target path & project name) works.
