### ISSUE TITLE
Post-fork commands

### ISSUE THREAD

**Issue by rcsilva83** [neva-dev/gradle-fork-plugin#46]
Hi,

Is it possible to execute a command line script inside the forked app's folder, like a git repo initialization? I could do something like `fork.finalizedBy gitInit` but I don't know how to get the generated folder path.

I also tried the following in 'fork.config' but it didn't work:

`action(Action { Runtime.getRuntime().exec("git init") })`

Could you help me?

Thanks in advance. Regards!

**Comment by rcsilva83** [comment]
I managed to do it this way:

1. Created a variable `newProjDir` which is set by `action(Action { newProjDir = config.targetDir.toString() })` on `config`
2. Created a task like this:


```
tasks {

  register("projInit", Exec::class) {
    dependsOn("fork")
    commandLine("echo", "do nothing")
    doLast {
      exec {
        if (newProjDir == null) {
          throw IllegalStateException("newProjDir is null!!!")
        }
        workingDir(newProjDir ?: "")
        commandLine("./init.sh")
      }
    }
  }
  named("fork") {
    finalizedBy("projInit")
  }
}
```
It isn't very clean but it worked. If you don't have a better solution, you may close the issue.

Regards,

Rodrigo

**Comment by pun-ky** [comment]
Define action in which you will use just `project.exec {}` 🙂

**Comment by rcsilva83** [comment]
Perfect! Thank you very much! I'm new to Gradle...

Regards!
