### ISSUE TITLE
Cannot use a property if it isn't used in the "config" session

### ISSUE THREAD

**Issue by rcsilva83** [neva-dev/gradle-fork-plugin#59]
Hi,

I have a property that is used on the controller of other property, like this:

```
    define("baseDir") {
      defaultValue = "/default/path"
    }
    define("targetPath") {
      enabled = false
      controller {
        value = other("baseDir").value + '/' + other("artifactId").value
      }
    }
```
The properity "baseDir" isn't used the "config" session, just in the "properties" session.

When I try to run "fork", I get the error `Property named 'baseDir' does not exist.` This always happen with properties that aren't used in the "config" session. Is there any way to override this behaviour?

Regards,

Rodrigo

**Comment by pun-ky** [comment]
try to declare property as `dynamic("props")`

**Comment by rcsilva83** [comment]
Thanks, @pun-ky . Unfortunately it didn't work...
```
    define("baseDir") {
      defaultValue = "/default/path"
      dynamic("baseDir")
    }
```

PS: Yes, I know my use case might be uncommon...

**Comment by pun-ky** [comment]
since defined properties are shared across configs dynamic method should be used in a form: `dynamic("configName")` so `dynamic("fork")`  or `dynamic("props")`

**Comment by rcsilva83** [comment]
`dynamic("fork")` worked! Thanks :)
